server:
  port: 8080
spring:
  datasource:
    url: ${DATA_SOURCE_URL:}
    username: ${DATA_SOURCE_USERNAME:}
    password: ${DATA_SOURCE_PASSWORD:}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 0.2
    vectorstore:
      pgvector:
        # initialize-schema: true
        schema-name: ${DATA_SOURCE_SCHEMA:}
        table-name: vector_store
        dimensions: 1536
        index-type: HNSW
        distance-type: COSINE_DISTANCE
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB